apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
spec:
  generators:
  - git:
      repoURL: https://github.com/saloyiana/Argocd-Sync-Wave
      revision: HEAD
      directories:
      - path: test-app
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/saloyiana/Argocd-Sync-Wave
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: test
