kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "test/data/test"
    argocd.argoproj.io/sync-wave: "4"
type: Opaque
stringData:
  sample-secret: <demo-key>
